import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import '@/assets/scss/main.scss'
import Navbar from '@/components/Navbar'
import Sidebar from "@/components/Sidebar";
import TopNavbar from "@/components/TopNavbar";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >

       <div className="flex justify-between h-full  m-auto">
           <Sidebar/>
       
           <div className="flex ml-12 mr-12 w-full flex-col">
              <TopNavbar/>
              {children}
             
          </div>
       </div>
       
      
      </body>
    </html>
  );
}
